# Generated by Django 3.2 on 2021-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=31)),
                ('units', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sp', models.IntegerField()),
                ('requests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limits', models.CharField(blank=True, max_length=20, null=True)),
                ('max', models.PositiveSmallIntegerField(db_column='Max')),
                ('enr', models.PositiveSmallIntegerField()),
                ('avl', models.SmallIntegerField()),
                ('wl', models.PositiveSmallIntegerField()),
                ('gm', models.CharField(max_length=2)),
                ('yl', models.IntegerField()),
                ('pr', models.IntegerField()),
                ('fr', models.IntegerField()),
                ('la', models.IntegerField()),
                ('qa', models.IntegerField()),
                ('format', models.CharField(db_column='Format', max_length=3)),
                ('xlist', models.CharField(max_length=20)),
                ('d1', models.CharField(max_length=5)),
                ('time1', models.CharField(max_length=15)),
                ('starttime1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('endtime1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d2', models.CharField(blank=True, max_length=5, null=True)),
                ('time2', models.CharField(blank=True, max_length=15, null=True)),
                ('starttime2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('endtime2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loc', models.CharField(max_length=10)),
                ('instructor', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'CourseInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(db_index=True, max_length=12)),
            ],
            options={
                'db_table': 'UserCourses',
                'managed': False,
            },
        ),
    ]
